
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sql1.db;
import sql1.db_bal; 


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author My
 */
public class balance extends javax.swing.JFrame {
   public String cp[]=new String[20];
  // public String cp_bal[]=new String[20];
    //  String out; 
    static   int p;
     static double bal[]=new double[10];
     String name[]=new String[20];
    
      //   cpin c1=new cpin();
         
     
   // public double  bal[]=new double[20];
    

    /**
     * Creates new form balance
     */
    public balance() {
     //   get();
        this.setUndecorated(true);
        
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        double width = toolkit.getScreenSize().getWidth();
        
        double height = toolkit.getScreenSize().getHeight();
        
        this.setSize((int)width, (int)height);
        initComponents();
       
      /*  p=c1.disp();
         System.out.println(p); */
    }
    public  void get() throws SQLException
    {
        cpin c1 = new cpin();
        p=c1.disp();
        bal=c1.bala();
        db db1=new db();
         name = db1.db_name();
       //  System.out.println(p);
       //  System.out.println(bal[p]);
         String out = String.valueOf(bal[p]);
      //  String out=Double.toString(bal[p]);
        //  out=new String(c);
        
     disp_bal.setText(out); 
     // p =c1.disp_n();
        
        disp_name.setText(name[p]);
    // jLabel1.setText(out);
    }
    //disp_bal.setText(bal[p]);
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        disp_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        disp_bal = new javax.swing.JTextField();
        text = new javax.swing.JLabel();
        atm_white_bg = new javax.swing.JLabel();
        card_slot = new javax.swing.JLabel();
        atm_bg = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(920, 280, 73, 23);
        jPanel1.add(disp_name);
        disp_name.setBounds(710, 220, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("HELLO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(600, 220, 100, 30);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(690, 330, 140, 40);

        disp_bal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        disp_bal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disp_balActionPerformed(evt);
            }
        });
        jPanel1.add(disp_bal);
        disp_bal.setBounds(620, 310, 180, 60);

        text.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        text.setText("YOUR BALANCE IS :");
        jPanel1.add(text);
        text.setBounds(590, 230, 250, 80);

        atm_white_bg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        atm_white_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmbg2.jpg"))); // NOI18N
        jPanel1.add(atm_white_bg);
        atm_white_bg.setBounds(520, 190, 380, 240);

        card_slot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardslot2.jpg"))); // NOI18N
        jPanel1.add(card_slot);
        card_slot.setBounds(900, 460, 100, 60);

        atm_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmbgkey.jpg"))); // NOI18N
        jPanel1.add(atm_bg);
        atm_bg.setBounds(350, 0, 720, 720);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/w1.jpg"))); // NOI18N
        jPanel1.add(BG);
        BG.setBounds(0, 0, 1370, 730);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1377, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disp_balActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disp_balActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disp_balActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        //  get();
        card c1=new card();
        c1.setVisible(true);
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(balance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         

        //System.out.println(c1.disp());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new balance().setVisible(true);
                    //     get();
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel atm_bg;
    private javax.swing.JLabel atm_white_bg;
    private javax.swing.JLabel card_slot;
    private javax.swing.JTextField disp_bal;
    private javax.swing.JTextField disp_name;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
